"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LEXICON_DATA_DIR = Path(os.environ['LEXICON_INVESTMENT_DATA_DIR']).resolve() if os.environ.get('LEXICON_INVESTMENT_DATA_DIR') else None
if LEXICON_DATA_DIR:
    LEXICON_DATA_DIR.mkdir(parents=True, exist_ok=True)

# Load .env file if exists
_env_path = (LEXICON_DATA_DIR / '.env') if LEXICON_DATA_DIR else BASE_DIR / '.env'
if _env_path.exists():
    for line in _env_path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            key, _, value = line.partition('=')
            os.environ.setdefault(key.strip(), value.strip())

# FinMind API token — 自動偵測 token 更換並回寫 SAVED_AT
FINMIND_TOKEN = os.environ.get('FINMIND_TOKEN', '')

if FINMIND_TOKEN and _env_path.exists():
    import hashlib
    from datetime import datetime

    _raw = _env_path.read_text(encoding='utf-8')
    _token_hash = hashlib.sha256(FINMIND_TOKEN.encode()).hexdigest()[:16]
    _old_hash = os.environ.get('FINMIND_TOKEN_HASH', '')

    if _token_hash != _old_hash:
        # Token 變了（或首次啟動），自動更新 SAVED_AT 和 HASH
        _now = datetime.now().strftime('%Y-%m-%dT%H:%M:%S')
        _updates = {
            'FINMIND_TOKEN_SAVED_AT': _now,
            'FINMIND_TOKEN_HASH': _token_hash,
        }
        _lines = _raw.splitlines()
        _existing_keys = set()
        _new_lines = []
        for _l in _lines:
            _stripped = _l.strip()
            if _stripped and not _stripped.startswith('#') and '=' in _stripped:
                _k = _stripped.partition('=')[0].strip()
                if _k in _updates:
                    _new_lines.append(f'{_k}={_updates[_k]}')
                    _existing_keys.add(_k)
                    continue
            _new_lines.append(_l)
        for _k, _v in _updates.items():
            if _k not in _existing_keys:
                _new_lines.append(f'{_k}={_v}')
        _env_path.write_text('\n'.join(_new_lines) + '\n', encoding='utf-8')
        os.environ['FINMIND_TOKEN_SAVED_AT'] = _now
        os.environ['FINMIND_TOKEN_HASH'] = _token_hash


# ── External API URLs ────────────────────────────────────────────
TWSE_BASE_URL = 'https://openapi.twse.com.tw/v1'
TPEX_BASE_URL = 'https://www.tpex.org.tw/openapi/v1'
ANUE_API_URL = 'https://api.cnyes.com/media/api/v1/newslist/category/tw_stock'
ETTODAY_RSS_URL = 'https://feeds.feedburner.com/ettoday/finance'
STOOQ_BASE_URL = 'https://stooq.com/q/d/l/'
FINMIND_BASE_URL = 'https://api.finmindtrade.com/api/v4/data'
GOODINFO_BASE_URL = 'https://goodinfo.tw/tw'
ANUE_SEARCH_URL = 'https://api.cnyes.com/media/api/v1/newslist/category/tw_stock'
EY_NEWS_URL = 'https://www.ey.gov.tw/Page/9277F759E41CCD91'
EY_BASE_URL = 'https://www.ey.gov.tw'
DATA_GOV_API_URL = 'https://data.gov.tw/datasets/export/json'

if LEXICON_DATA_DIR:
    _secret_path = LEXICON_DATA_DIR / 'django-secret'
    try:
        _descriptor = os.open(_secret_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(_descriptor, 'w', encoding='utf-8') as _secret_file:
            _secret_file.write(secrets.token_urlsafe(48))
    except FileExistsError:
        pass
    SECRET_KEY = _secret_path.read_text(encoding='utf-8')
else:
    SECRET_KEY = 'lexicon-investment-local-development-only'

DEBUG = not bool(LEXICON_DATA_DIR)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
    'market',
    'account',
    'screener',
    'strategy',
    'learning',
    'news',
    'notes',
    'analysis',
    'trading_core',
    'scanner',
    'trader',
    'watchdog',
    'exiter',
    'bookkeeper',
    'risk_guard',
    'pipeline',
    'user_profile.apps.ProfileConfig',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = (LEXICON_DATA_DIR / 'media') if LEXICON_DATA_DIR else BASE_DIR / 'media'

# Channels (ASGI + WebSocket)
ASGI_APPLICATION = 'backend.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MIDDLEWARE = [
    'core.loopback.LoopbackOriginMiddleware',
    'core.middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS
CORS_ALLOWED_ORIGINS = [] if LEXICON_DATA_DIR else [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_HEADERS = [*default_headers, 'x-request-id']
CORS_EXPOSE_HEADERS = ['X-Request-ID']

# DRF
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'UNAUTHENTICATED_USER': None,
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': (LEXICON_DATA_DIR / 'investment.sqlite3') if LEXICON_DATA_DIR else BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ---------------------------------------------------------------------------
# Logging — 彩色 console 輸出，方便區分不同模組和錯誤等級
# ---------------------------------------------------------------------------

import logging
import copy


class ColoredFormatter(logging.Formatter):
    """根據 log level 與 module 名稱上色。"""

    LEVEL_COLORS = {
        'DEBUG':    '\033[36m',     # cyan
        'INFO':     '\033[32m',     # green
        'WARNING':  '\033[33m',     # yellow
        'ERROR':    '\033[31m',     # red
        'CRITICAL': '\033[1;31m',   # bold red
    }
    MODULE_COLORS = {
        'core.shioaji':     '\033[35m',   # magenta
        'account.service':  '\033[34m',   # blue
        'market.quote':     '\033[36m',   # cyan
        'market.twse':      '\033[33m',   # yellow
        'news.service':     '\033[32m',   # green
        'market.views':     '\033[95m',   # light magenta
        'screener.service': '\033[96m',   # light cyan
        'strategy.service': '\033[94m',   # light blue
    }
    RESET = '\033[0m'

    def format(self, record):
        record = copy.copy(record)
        level_color = self.LEVEL_COLORS.get(record.levelname, '')
        module_color = self.MODULE_COLORS.get(record.name, '\033[37m')  # default white
        record.levelname = f"{level_color}{record.levelname:<8}{self.RESET}"
        record.name = f"{module_color}{record.name}{self.RESET}"
        return super().format(record)


LOG_DIR = (LEXICON_DATA_DIR / 'logs') if LEXICON_DATA_DIR else BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'colored': {
            '()': ColoredFormatter,
            'format': '{levelname} {name} | {message}',
            'style': '{',
        },
        'file': {
            'format': '{asctime} {levelname:<8} {name} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'colored',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 10,
            'encoding': 'utf-8',
            'formatter': 'file',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'market': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'account': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'screener': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'strategy': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'news': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'analysis': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'scanner': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'trader': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'watchdog': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'exiter': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'bookkeeper': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'risk_guard': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Existing module loggers keep their console output and also write to the log file.
for _logger_config in LOGGING['loggers'].values():
    _logger_config.setdefault('handlers', [])
    if 'file' not in _logger_config['handlers']:
        _logger_config['handlers'].append('file')

LOGGING['loggers'].update({
    'api.request': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
        'propagate': False,
    },
    'django.request': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
        'propagate': False,
    },
})

LOGGING['root'] = {
    'handlers': ['console', 'file'],
    'level': 'INFO',
}
