# Generated by Django 5.2.13 on 2026-04-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=16)),
                ("score", models.FloatField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("consumed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=16)),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=8
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(
                        help_text="Shares (multiples of 1000 for TWSE common lot)"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("market", "Market"), ("limit", "Limit")],
                        default="market",
                        max_length=8,
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        blank=True,
                        help_text="Limit price; null for market order",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Broker order id",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=16)),
                ("qty", models.IntegerField()),
                ("avg_cost", models.FloatField()),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=8,
                    ),
                ),
                (
                    "entry_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_positions",
                        to="trading_core.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="ExitSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("stop_loss", "Stop Loss"),
                            ("take_profit", "Take Profit"),
                            ("manual", "Manual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("triggered_price", models.FloatField()),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_signals",
                        to="trading_core.position",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=16)),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=8
                    ),
                ),
                ("qty", models.IntegerField()),
                ("price", models.FloatField()),
                ("executed_at", models.DateTimeField(db_index=True)),
                (
                    "pnl",
                    models.FloatField(
                        blank=True,
                        help_text="Realised P&L; only set on closing trades",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="trading_core.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
    ]
