# Generated by Django 5.2.17 on 2026-09-27 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading_core.candidate'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_ref',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exit_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading_core.exitsignal'),
        ),
        migrations.AddField(
            model_name='order',
            name='filled_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='filled_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading_core.position'),
        ),
        migrations.AddField(
            model_name='order',
            name='venue',
            field=models.CharField(choices=[('paper', 'Paper'), ('broker_simulation', 'Broker simulation'), ('broker_production', 'Broker production')], db_index=True, default='paper', max_length=24),
        ),
        migrations.AddField(
            model_name='position',
            name='venue',
            field=models.CharField(choices=[('paper', 'Paper'), ('broker_simulation', 'Broker simulation'), ('broker_production', 'Broker production')], db_index=True, default='paper', max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('partially_filled', 'Partially filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='BrokerFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('executed_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='trading_core.order')),
            ],
        ),
    ]
