# Generated by Django 5.2.13 on 2026-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_positions",
                    models.IntegerField(
                        default=5, help_text="Maximum concurrent open positions"
                    ),
                ),
                (
                    "max_position_pct",
                    models.FloatField(
                        default=25.0,
                        help_text="Maximum single position as % of capital",
                    ),
                ),
                (
                    "max_daily_loss",
                    models.FloatField(
                        default=-50000.0,
                        help_text="Block new entries when today realised PnL <= this",
                    ),
                ),
                (
                    "blacklist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of symbols that may never be traded",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
