# Generated by Django 6.0.4 on 2026-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
