# Generated by Django 5.2.17 on 2026-09-27 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='其他', max_length=64)),
                ('tags', models.JSONField(default=list)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
